### ISSUE TITLE
My issue

### ISSUE THREAD

**Issue by DavidRayner** [promod/CoD-PunkBuster-Files#4]
I'm sure this is an issue with my setup rather than with your work here but some help would be great!

I manage a VPS to run game servers etc for a gaming community. I'm planning to migrate the VPS to Debian soon and therefore I've rented an extra VPS to test things with Debian (Jessie 64bit).

I'm struggling to get PB working with cod2. When using pbsetup.run I get the following error:

"Error #0100: ERROR: The update attempt failed because the file "http://websec.evenbalance.com:6080/downloads/pbgame.htm" is missing on the update servers.  Please try again later."

I've added the evenbalance address in my hosts file to direct them to localhost and also have the downloads folder in the web server.
Thus when attempting to update using the local server I get the following:
"PBSetup v3.2
Downloading pbgame.htm
Downloading pbsecsv.htm
The client for "cod2" is updating
Error #0112: ERROR: Could not convert /tmp/pbsVp9wS0 to /var/www/html/cod2/pb/dll/lc002208.so."

Do you know what can cause this?

When using the 64-bit pbsetup you aren't able to add CoD2 since it's a 32-bit game, so I am of course using the 32-bit pbsetup. 

Are you aware of any dependencies I may be missing?

Thanks!

**Comment by Ingramz** [comment]
The point of modifying hosts file is so that you would set up your own web server with those files, I guess I did not write about that. It is quite hacky and usually not worth the effort as Call of Duty files will not be updated anyway.

PBSetup is not required as all of the files that you need for the server(s) have already been downloaded using that method and uploaded to this repository. So if you want files for CoD2 under linux, take Call of Duty 2/Linux/pb folder and put it inside the game folder (same level with executable binaries and main folder). This way you'll save yourself some headaches and probably make the process (if it is automated) faster because pbsetup is slow.

**Comment by DavidRayner** [comment]
EDIT:

I was getting error

"PunkBuster Server: Preparing to Disable PB Server... (/root/cod2/servers/ctf/pb/)"

I hoped building them from pb setup would help this issue.

I've fixed the issue now, honestly not sure how.

Thanks anyhow!

**Comment by Ingramz** [comment]
Could you paste the output of `cd /root/cod2/servers/ctf && ls -als && md5sum cod2_lnxded` and the startup script, if you have one.
